# Generated by Django 6.0.1 on 2026-01-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='in_app_communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('I’m a man', 'I’m a man'), ('I’m a woman', 'I’m a woman'), ('Another gender', 'Another gender')], max_length=150, null=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('nowlii_name', models.CharField(blank=True, choices=[('milo', 'milo'), ('bloop', 'bloop'), ('gumo', 'gumo'), ('knotty', 'knotty'), ('Fizzy', 'Fizzy'), ('zee', 'zee')], max_length=50, null=True)),
                ('custom_nowlii_name', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(blank=True, choices=[('English', 'English'), ('Deutsch', 'Deutsch'), ('Espanol', 'Espanol')], default='English', max_length=50, null=True)),
                ('voice', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, choices=[('English', 'English'), ('Deutsch', 'Deutsch'), ('Espanol', 'Espanol')], default='English', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('paid_user', models.BooleanField(default=False)),
                ('current_plan', models.CharField(choices=[('free', 'free'), ('monthly', 'monthly'), ('yearly', 'yearly')], default='free', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'swappable': 'AUTH_USER_MODEL',
            },
        ),
    ]
