# Generated by Django 6.0.1 on 2026-01-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_forgotpasswordrequest_pendinguser_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppCommunication',
            new_name='Profile',
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
