# Generated by Django 6.0.1 on 2026-04-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_appcommunication_profile_pendinguser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
