# Generated by Django 6.0.1 on 2026-04-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customusermodel_first_name_customusermodel_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='avatar_logo',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
