# Generated by Django 6.0.1 on 2026-04-06 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_user'),
        ('users', '0005_rename_avatar_profile_avatar_logo_and_more'),
    ]

    operations = [
    ]
