# Generated by Django 6.0.1 on 2026-04-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20260406_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nowlii_name',
            field=models.CharField(blank=True, choices=[('milo', 'milo'), ('bloop', 'bloop'), ('gumo', 'gumo'), ('knotty', 'knotty'), ('fizzy', 'fizzy'), ('zee', 'zee')], max_length=50, null=True),
        ),
    ]
