# Generated by Django 6.0.1 on 2026-04-09 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_nowlii_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NowliiPredefinedOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('avatar_logo', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='nowlii_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='predefined_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.nowliipredefinedoption'),
        ),
    ]
