# Generated by Django 6.0.1 on 2026-04-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_nowliipredefinedoption_alter_profile_nowlii_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[("I'm a man", "I'm a man"), ("I'm a woman", "I'm a woman"), ('Another gender', 'Another gender')], max_length=150, null=True),
        ),
    ]
