# Generated by Django 6.0.1 on 2026-05-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowliipredefinedoption',
            name='avatar_logo',
            field=models.URLField(help_text='The URL to the avatar image/logo for this Nowlii character'),
        ),
        migrations.AlterField(
            model_name='nowliipredefinedoption',
            name='name',
            field=models.CharField(help_text="The unique name of the Nowlii character (e.g., 'Sparky')", max_length=50, unique=True),
        ),
    ]
