# Generated by Django 6.0.1 on 2026-05-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowliipredefinedoption',
            name='avatar_logo',
            field=models.ImageField(blank=True, help_text='The avatar image/logo for this Nowlii character', null=True, upload_to='nowlii_logos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_logo',
            field=models.ImageField(blank=True, null=True, upload_to='user_avatars/'),
        ),
    ]
