# Generated by Django 6.0.1 on 2026-07-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_nowliipredefinedoption_avatar_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nowliipredefinedoption',
            name='voice',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', help_text="Voice used for this companion's AI call (Male/Female).", max_length=10),
        ),
    ]
