# Generated by Django 6.0.1 on 2026-07-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_seed_companion_voices'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rest_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
