# Generated by Django 6.0.1 on 2026-08-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_rest_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowliipredefinedoption',
            name='voice',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Female', help_text="Voice used for this companion's AI call (Male/Female).", max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='voice',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Female', max_length=50, null=True),
        ),
    ]
