# Generated by Django 6.0.1 on 2026-08-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_nowliipredefinedoption_voice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='restricted_topics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='use_data_to_improve',
            field=models.BooleanField(default=True),
        ),
    ]
