# Generated by Django 6.0.1 on 2026-01-23 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, max_length=200, null=True)),
                ('zone', models.CharField(blank=True, choices=[('Soft steps', 'Soft steps'), ('Elevated', 'Elevated'), ('Power move', 'Power move'), ('Stretch zone', 'Stretch zone')], max_length=100, null=True)),
                ('due_date', models.CharField(blank=True, choices=[('Today', 'Today'), ('Tomorrow', 'Tomorrow')], max_length=50, null=True)),
                ('select_a_date', models.DateField(blank=True, null=True)),
                ('due_time', models.TimeField(null=True)),
                ('enable_call', models.BooleanField(default=False)),
                ('repeat_quest', models.BooleanField(default=False)),
                ('set_alarm', models.BooleanField(default=False)),
                ('task_done', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Quests',
            },
        ),
        migrations.CreateModel(
            name='SubTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='quests.quests')),
            ],
            options={
                'verbose_name_plural': 'subtasks',
            },
        ),
    ]
