# Generated by Django 6.0.1 on 2026-03-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quests',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
