# Generated by Django 6.0.1 on 2026-04-05 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quests',
            name='due_date',
        ),
    ]
