# Generated by Django 6.0.1 on 2026-04-06 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0003_quests_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtasks',
            old_name='is_complete',
            new_name='task_done',
        ),
        migrations.RenameField(
            model_name='subtasks',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='quests',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
