# Generated by Django 6.0.1 on 2026-04-06 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_alter_quests_due_time'),
        ('quests', '0004_rename_is_complete_subtasks_task_done_and_more'),
    ]

    operations = [
    ]
