# Generated by Django 6.0.1 on 2026-04-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0005_merge_20260406_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quests',
            old_name='due_time',
            new_name='select_a_time',
        ),
    ]
