# Generated by Django 6.0.1 on 2026-07-14 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(help_text='First billing day; anchors the phase schedule.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('lifetime_free', 'Lifetime free'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('platform', models.CharField(choices=[('mock', 'Mock'), ('apple', 'Apple'), ('google', 'Google')], default='mock', max_length=10)),
                ('lifetime_free', models.BooleanField(default=False)),
                ('cancelled_at', models.DateField(blank=True, null=True)),
                ('store_transaction_id', models.CharField(blank=True, max_length=255)),
                ('store_token', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
    ]
