# Generated by Django 6.0.1 on 2026-08-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_trial_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='step_down_pending_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='store_product_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
