# Generated by Django 6.0.1 on 2026-09-21 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_stripeevent_subscription_cancel_at_period_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=255, unique=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_months', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['period_start'],
            },
        ),
    ]
