# Generated by Django 6.0.1 on 2026-07-03 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'user'), ('admin', 'admin')], default='user', max_length=10)),
                ('category', models.CharField(blank=True, choices=[('App issue', 'App issue'), ('Billing & Subscription', 'Billing & Subscription'), ('Question about features', 'Question about features'), ('Feedback or suggestion', 'Feedback or suggestion'), ('Other', 'Other')], max_length=50, null=True)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support message',
                'verbose_name_plural': 'Support messages',
                'ordering': ['created_at'],
            },
        ),
    ]
