# Generated by Django 6.0.1 on 2026-07-06 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=64, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('extension_used', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voice call',
                'verbose_name_plural': 'Voice calls',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'started_at'], name='voice_calls_user_id_d6b218_idx')],
            },
        ),
    ]
