# Generated by Django 6.0.1 on 2026-07-07 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_calls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallEmotionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy', models.FloatField(default=0)),
                ('motivated', models.FloatField(default=0)),
                ('angry', models.FloatField(default=0)),
                ('tired', models.FloatField(default=0)),
                ('sad', models.FloatField(default=0)),
                ('dominant_emotion', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_snapshot', to='voice_calls.voicecall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_emotion_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Call emotion snapshot',
                'verbose_name_plural': 'Call emotion snapshots',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='voice_calls_user_id_d2f40a_idx')],
            },
        ),
    ]
