# Generated by Django 6.0.1 on 2026-07-07 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_calls', '0002_callemotionsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLowMoodSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrases', models.JSONField(default=list)),
                ('dominant_category', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='low_mood_snapshot', to='voice_calls.voicecall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_low_mood_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Call low-mood snapshot',
                'verbose_name_plural': 'Call low-mood snapshots',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='voice_calls_user_id_ad3331_idx')],
            },
        ),
    ]
