# Generated by Django 6.0.1 on 2026-07-28 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_calls', '0003_calllowmoodsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_detected', models.TextField(blank=True)),
                ('focus_topic', models.TextField(blank=True)),
                ('energy_shift', models.TextField(blank=True)),
                ('next_step', models.TextField(blank=True)),
                ('dominant_emotion', models.CharField(blank=True, max_length=20)),
                ('top_emotions', models.JSONField(blank=True, default=dict)),
                ('language', models.CharField(blank=True, max_length=8)),
                ('total_turns', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='voice_calls.voicecall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Call summary',
                'verbose_name_plural': 'Call summaries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='voice_calls_user_id_e7f25a_idx')],
            },
        ),
    ]
