# Generated by Django 6.0.1 on 2026-07-30 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0006_rename_due_time_quests_select_a_time'),
        ('voice_calls', '0004_callsummary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('local_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_call', to='voice_calls.voicecall')),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_calls', to='quests.quests')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scheduled call',
                'verbose_name_plural': 'Scheduled calls',
                'ordering': ['scheduled_for'],
                'indexes': [models.Index(fields=['user', 'local_date'], name='voice_calls_user_id_4873cc_idx'), models.Index(fields=['user', 'status', 'scheduled_for'], name='voice_calls_user_id_698df6_idx')],
            },
        ),
    ]
