# Generated by Django 6.0.1 on 2026-07-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_calls', '0005_scheduledcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsummary',
            name='words_circled',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
