# Generated by Django 6.0.1 on 2026-08-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_calls', '0006_callsummary_words_circled'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsummary',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='callsummary',
            name='note_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
