# Generated by Django 6.0.1 on 2026-08-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_calls', '0007_callsummary_note_callsummary_note_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsummary',
            name='tiny_question',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
